name: NASA Project CI
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu:latest
    env:
      CI: true
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version ${{ matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version}} 
      - name: install dependencies
        run: npm install
      - name: building frontend 
        run: npm run build --prefix client
      - name: running tests 
        run: npm run test 
